name: build

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore dotnet packages
        run: dotnet restore "World Prefabs.sln"

      - name: Restore NuGet packages
        run: nuget restore "World Prefabs.sln"

      - name: Build Unity
        uses: game-ci/unity-builder@v2.0.4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Inspect
        run: pwd; ls -l
        shell: pwsh
