name: Build VLC Unity plugin

on:
  workflow_dispatch: {}

jobs:
  libvlcsharp:
    name: Build LibVLCSharp

    runs-on: ubuntu-latest

    steps:
      - name: Build LibVLCSharp
        shell: bash

        run: |
          wget https://download.visualstudio.microsoft.com/download/pr/17b6759f-1af0-41bc-ab12-209ba0377779/e8d02195dbf1434b940e0f05ae086453/dotnet-sdk-6.0.100-linux-x64.tar.gz
          mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-6.0.100-linux-x64.tar.gz -C $HOME/dotnet
          export DOTNET_ROOT=$HOME/dotnet
          export PATH=$PATH:$HOME/dotnet
          dotnet --version
          mkdir tmp && cd tmp && git clone https://code.videolan.org/videolan/LibVLCSharp lvs
          cd lvs
          git checkout -f master
          dotnet publish src/LibVLCSharp/LibVLCSharp.csproj /p:UNITY=true -c Release

      - name: Build VLC-Unity
        shell: bash

        run: |
          mkdir -p nightlies
          wget https://artifacts.videolan.org/vlc/nightly-win64/20220804-0423/vlc-4.0.0-dev-win64-debug-2d8beeb2.7z -O ./nightlies/vlc-4.0.0-dev-win64.7z
          7z x ./nightlies/vlc-4.0.0-dev-win64.7z -o./build
          rm -f ./nightlies/vlc-4.0.0-dev-win64.7z
          mkdir -p Assets/VLCUnity/Plugins/x86_64
          cp -R ./build/vlc-4.0.0-dev/{libvlc.dll,libvlccore.dll,hrtfs,lua,plugins} Assets/VLCUnity/Plugins/x86_64
          rm -rf Assets/VLCUnity/Plugins/x86_64/lua/http
          cp -r ./build/vlc-4.0.0-dev/sdk/ PluginSource/
          ./build.sh -r
