version: "2.4"

services:
  grafana:
    image: grafana/grafana-oss:9.0.0-beta1
    ports:
      - 3001:3000
    links:
      - graphite
    volumes:
      - ./.ignored/data/grafana:/var/lib/grafana

  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-1
    ports:
    - 3080:80
    - 2003:2003
    - 8125:8125
    - 8125:8125/udp
    volumes:
    - ./.ignored/data/graphite:/opt/graphite/storage

  redis:
    image: redis:7.0.0-alpine3.16
    ports:
      - 3306:3306
    volumes:
      - ./.ignored/data/redis:/data
