name: build

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"

  pull_request:
    branches: [ "master" ]

jobs:

########################
# Caching dependencies #
########################
  update-game:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2

      - name: Fetch game update info
        run: |
          Invoke-WebRequest https://api.steamcmd.net/v1/info/661130 -OutFile info.json

      - name: Cache game files
        id: cache-game-files
        uses: actions/cache@v2
        with:
          path: chilloutvr
          key: cvr-${{ hashFiles('./info.json') }}
          restore-keys: |
            cvr-

      - name: Setup ChilloutVR
        uses: DecentM/setup-steam-game-windows@v1.0.0
        if: steps.cache-game-files.outputs.cache-hit != 'true'
        with:
          username: ${{ secrets.STEAM_USER }}
          password: ${{ secrets.STEAM_PASSWORD }}
          gameid: 661130
          folder: chilloutvr

########################
#       Building       #
########################
  build-prefabs-source:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: prefabs-source

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get yt-dlp
        env:
          YT_DLP_VERSION: "2022.07.18"
          YT_DLP_FILE: "yt-dlp.exe"
        run: |
          set -e
          set +x

          mkdir -p ./dll-build/UserLibs

          YT_DLP_URL=https://github.com/yt-dlp/yt-dlp/releases/download/$YT_DLP_VERSION/$YT_DLP_FILE
          wget $YT_DLP_URL -O ./dll-build/UserLibs/$YT_DLP_FILE

      - name: Cache
        uses: actions/cache@v2
        with:
          path: prefabs-source/Library
          key: prefabs-source-Library-${{ hashFiles('prefabs-source/Assets/**', 'prefabs-source/Packages/**', 'prefabs-source/ProjectSettings/**') }}
          restore-keys: |
            prefabs-source-Library-

      - name: Create Unity build
        uses: game-ci/unity-builder@v2.0.4
        with:
          projectPath: prefabs-source
          buildsPath: prefabs-source/build
          unityVersion: 2019.4.31f1
          allowDirtyBuild: true
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Copy files to destination
        run: |
          set -e
          set +x

          mkdir -p ./dll-build/UserLibs
          DIR=build/StandaloneWindows64/StandaloneWindows64_Data
          cp -a $DIR/Plugins/x86_64/* $DIR/Managed/LibVLCSharp.dll $DIR/Managed/DecentM.*.dll ./dll-build/UserLibs

      - name: Create zip
        uses: vimtor/action-zip@v1
        with:
          files: prefabs-source/dll-build/
          dest: DecentM.Components.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: DecentM.Components.zip

      - name: Upload built DLLs
        uses: actions/upload-artifact@v2
        with:
          name: DecentM.Prefabs.Raw
          path: prefabs-source/dll-build

  build-mods:
    runs-on: windows-latest

    needs:
      - build-prefabs-source
      - update-game

    defaults:
      run:
        shell: pwsh
        working-directory: mods

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: DecentM.Prefabs.Raw
        path: prefabs

    - name: Bootstrap CI
      run: tools/bootstrap_ci.ps1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Upload outputs
      uses: actions/upload-artifact@v2
      with:
        name: DecentM.Mods
        path: .\mods\chilloutvr\Mods\*.dll

  build-prefabs:
    runs-on: ubuntu-latest

    needs:
      - build-prefabs-source

    defaults:
      run:
        shell: bash
        working-directory: prefabs

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: prefabs/Library
          key: prefabs-Library-${{ hashFiles('prefabs/Assets/**', 'prefabs/Packages/**', 'prefabs/ProjectSettings/**') }}
          restore-keys: |
            prefabs-Library-

      - name: Create Unity build
        uses: game-ci/unity-builder@v2.0.4
        with:
          projectPath: prefabs
          buildsPath: prefabs/build
          unityVersion: 2019.4.31f1
          buildMethod: PackageExporter.ExportPackage
          allowDirtyBuild: true
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload built unitypackage
        uses: actions/upload-artifact@v2
        with:
          name: Unitypackage
          path: prefabs/output/DecentM.Prefabs.unitypackage

  release-installables:
    runs-on: ubuntu-latest

    needs:
      - build-prefabs
      - build-mods

    defaults:
      run:
        shell: bash

    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: DecentM.Prefabs.Raw

      - uses: actions/download-artifact@v2
        with:
          name: Unitypackage

      - uses: actions/download-artifact@v2
        with:
          name: DecentM.Mods

      - name: Create mods zip
        uses: vimtor/action-zip@v1
        with:
          files: |
            mods/output/
            UserLibs
          dest: DecentM.Mods.zip

      - name: Release mods
        uses: softprops/action-gh-release@v1
        with:
          files: |
            prefabs/output/DecentM.Prefabs.unitypackage
            DecentM.Mods.zip
