name: build

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"

  pull_request:
    branches: [ "master" ]

jobs:
  build-dlls:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: prefabs-source

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Unity build
        uses: game-ci/unity-builder@v2.1.2
        with:
          projectPath: prefabs-source
          buildsPath: prefabs-source/build
          unityVersion: 2019.4.31f1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload outputs
        uses: actions/upload-artifact@v3
        with:
          name: ScriptAssemblies
          path: prefabs-source/Library/ScriptAssemblies

  determine-matrix:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: prefabs-source

    outputs:
      folders: ${{ steps.jobs.outputs.folders }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine package list
        id: jobs
        run: |
          set -exu

          cd Packages
          echo folders=$(tree -J -d -L 1 | jq -c '.[0].contents | map(.name)') >> $GITHUB_OUTPUT

########################
#       Prefabs        #
########################
  publish-prefabs:
    name: publish-${{ matrix.folder }}

    runs-on: ubuntu-latest

    needs:
      - determine-matrix

    strategy:
      matrix:
        folder: ${{ fromJson(needs.determine-matrix.outputs.folders) }}

    defaults:
      run:
        shell: bash
        working-directory: prefabs-source

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com/@decentm'

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          file-name: prefabs-source/Packages/${{ matrix.folder }}/package.json

      - name: Publish if updated
        if: steps.check.outputs.changed == 'true'
        run: |
          set -exu
          git subtree split -P prefabs-source/Packages/${{ matrix.folder }} -b release/${{ matrix.folder }}/${{ steps.check.outputs.version }}
          git push origin release/${{ matrix.folder }}/${{ steps.check.outputs.version }}

########################
#         Mods         #
########################
  build-mods:
    runs-on: windows-latest

    needs:
      - build-dlls

    defaults:
      run:
        shell: pwsh
        working-directory: mods

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: ScriptAssemblies
        path: prefabs-source/Library/ScriptAssemblies

    - name: Fetch game update info
      id: game-info
      run: |
        $build_info = Invoke-RestMethod -Uri https://api.steamcmd.net/v1/info/661130
        echo hash=$build_info.data.'661130'.'_sha' >> $GITHUB_OUTPUT

    - name: Cache game files
      id: cache-game-files
      uses: actions/cache@v3
      with:
        path: mods/chilloutvr
        key: cvr-${{ steps.game-info.outputs.hash }}
        restore-keys: |
          cvr-

    - name: Setup ChilloutVR
      uses: DecentM/setup-steam-game-windows@v1.0.0
      if: steps.cache-game-files.outputs.cache-hit != 'true'
      with:
        username: ${{ secrets.STEAM_USER }}
        password: ${{ secrets.STEAM_PASSWORD }}
        gameid: 661130
        folder: mods/chilloutvr

    - name: Bootstrap CI
      run: tools/bootstrap_ci.ps1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Upload outputs
      uses: actions/upload-artifact@v3
      with:
        name: Mods
        path: mods/Mods/*/bin/Release/
