name: build

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"

  pull_request:
    branches: [ "master" ]

jobs:

########################
#       Prefabs        #
########################
  build-prefabs-source:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: prefabs-source

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get yt-dlp
        env:
          YT_DLP_VERSION: "2023.01.06"
          YT_DLP_FILE: "yt-dlp.exe"
        run: |
          set -e
          set -x

          mkdir -p ./dll-build/UserLibs

          YT_DLP_URL=https://github.com/yt-dlp/yt-dlp/releases/download/$YT_DLP_VERSION/$YT_DLP_FILE
          wget $YT_DLP_URL -O ./dll-build/UserLibs/$YT_DLP_FILE

      - name: Cache
        uses: actions/cache@v3
        with:
          path: prefabs-source/Library
          key: prefabs-source-Library-${{ hashFiles('prefabs-source/Assets/**/*', 'prefabs-source/Packages/**/*', 'prefabs-source/ProjectSettings/**/*') }}
          restore-keys: |
            prefabs-source-Library-

      - name: Create Unity build
        uses: game-ci/unity-builder@v2.0.4
        with:
          projectPath: prefabs-source
          buildsPath: prefabs-source/build
          unityVersion: 2019.4.31f1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com/@decentm'

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -exu

          for f in Packages/*; do
              if [ -d "$f" ]; then
                  cd "$f"

                  cp $NPM_CONFIG_USERCONFIG .
                  yarn publish --access=public

                  cd -
              fi
          done

########################
#         Mods         #
########################
  build-mods:
    runs-on: windows-latest

    needs:
      - build-prefabs-source

    defaults:
      run:
        shell: pwsh
        working-directory: mods

    steps:
    - uses: actions/checkout@v3

    - name: Fetch game update info
      id: game-info
      run: |
        Invoke-WebRequest https://api.steamcmd.net/v1/info/661130 -OutFile info.json
        $hashinfo = Get-FileHash info.json
        echo "hash=$($hashinfo.hash)" >> $GITHUB_OUTPUT

    - name: Cache game files
      id: cache-game-files
      uses: actions/cache@v3
      with:
        path: mods/chilloutvr
        key: cvr-${{ steps.game-info.outputs.hash }}
        restore-keys: |
          cvr-

    - name: Setup ChilloutVR
      uses: DecentM/setup-steam-game-windows@v1.0.0
      if: steps.cache-game-files.outputs.cache-hit != 'true'
      with:
        username: ${{ secrets.STEAM_USER }}
        password: ${{ secrets.STEAM_PASSWORD }}
        gameid: 661130
        folder: mods/chilloutvr

    - uses: actions/download-artifact@v2
      with:
        name: DecentM.UserLibs
        path: mods/prefabs

    - name: Bootstrap CI
      run: tools/bootstrap_ci.ps1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Upload outputs
      uses: actions/upload-artifact@v2
      with:
        name: DecentM.Mods
        path: .\mods\chilloutvr\Mods\*.dll
